name: test

on:
  push:
  pull_request:

jobs:
  unit:
    name: "PHPUnit tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
          - '7.3'
          - '7.4'
          - '8.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: ""
          php-version: "${{ matrix.php-versions }}"
          tools: "composer:v2"

      - name: Install dependencies
        run: composer install --no-progress --ansi --prefer-dist --optimize-autoloader

      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
